---
- name: atom hydrogen plugin dependencies
  become: yes
  become_user: root
  with_items: '{{atom_hydrogen_dep_pkgs|default([])}}'
  package:
    name: '{{item}}'
    state: present

- name: upgrade pip
  become: yes
  become_user: root
  pip:
    name: pip
    state: latest

- name: atom plugin dependency ipython[notebook]
  become: yes
  become_user: root
  pip:
    name: 'ipython[notebook]'
    state: present

- name: install atom hydrogen plugin
  become: yes
  become_user: root
  command: apm install hydrogen
  changed_when: False
