---
- name: download atom pkg
  become: yes
  become_user: root
  get_url:
    url: '{{atom_pkg_url}}'
    dest: /tmp/{{atom_pkg}}
    checksum: '{{atom_pkg_checksum}}'
    mode: 0644

- include: '{{atom_pkg_installer|default("pkg")}}.yml'

- include: hydrogen.yml
  when: '{{atom_hydrogen_enable}}'
  
